// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Analizadores/Lexer.flex

package Analizadores;
import java_cup.runtime.Symbol;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  3,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  6,  7,  8,  9,  0, 10, 11, 12, 13, 14, 15, 16, 17, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 20, 21, 22, 23,  6, 
     0, 24, 25, 26, 27, 28, 29, 25, 30, 31, 25, 25, 25, 25, 32, 33, 
    34, 25, 35, 36, 25, 37, 25, 38, 25, 25, 25, 39,  0, 40,  0, 41, 
     0, 42, 25, 43, 44, 45, 46, 25, 47, 48, 25, 25, 49, 50, 51, 52, 
    53, 25, 54, 55, 56, 57, 25, 25, 25, 25, 25, 58, 59, 60,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\5"+
    "\1\3\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\5\24\1\25"+
    "\1\26\1\6\4\24\1\27\1\2\1\30\1\31\1\32"+
    "\1\33\1\3\1\6\1\2\1\16\1\34\1\24\1\0"+
    "\4\24\1\6\5\24\1\16\1\0\11\24\1\16\1\0"+
    "\7\24\1\35\1\5\1\0\7\24\1\5\1\0\5\24"+
    "\1\0\1\24\1\5\1\0\3\24\1\36\1\24\1\0"+
    "\1\24\1\37\1\40\2\24\1\41\1\24\1\0\4\24"+
    "\1\0\15\24\1\42\1\24\1\43\1\24\1\44\1\24"+
    "\1\45\1\24\1\46\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\75\0\364\0\u0131\0\u016e"+
    "\0\u01ab\0\364\0\364\0\u01e8\0\u01e8\0\75\0\u0225\0\u0262"+
    "\0\u029f\0\75\0\75\0\u02dc\0\u0319\0\u0356\0\u0393\0\u03d0"+
    "\0\u040d\0\u044a\0\u0487\0\75\0\75\0\u04c4\0\u0501\0\u053e"+
    "\0\u057b\0\u05b8\0\75\0\u05f5\0\75\0\75\0\75\0\75"+
    "\0\364\0\u0632\0\u066f\0\u06ac\0\75\0\u06e9\0\u0726\0\u0763"+
    "\0\u07a0\0\u07dd\0\u081a\0\u0857\0\u0894\0\u08d1\0\u090e\0\u094b"+
    "\0\u0988\0\u09c5\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6\0\u0b33"+
    "\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde\0\u0d1b"+
    "\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0393\0\u0e89\0\u0ec6"+
    "\0\u0f03\0\u0f40\0\u0f7d\0\u0fba\0\u0ff7\0\u1034\0\u1071\0\u10ae"+
    "\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\u1259\0\u1296"+
    "\0\u12d3\0\u1310\0\u134d\0\u138a\0\u13c7\0\u0393\0\u1404\0\u1441"+
    "\0\u147e\0\u12d3\0\u14bb\0\u14f8\0\u1535\0\u0393\0\u1572\0\u15af"+
    "\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a\0\u1797"+
    "\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8\0\u1905\0\u1942\0\u197f"+
    "\0\u19bc\0\u19f9\0\u0393\0\u1a36\0\u1a73\0\u1ab0\0\u0393\0\u1aed"+
    "\0\75\0\u1b2a\0\u0393\0\u0393";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\2"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\2\27"+
    "\1\30\2\27\1\31\4\27\1\32\2\27\1\33\1\27"+
    "\1\34\1\35\1\36\4\27\1\37\1\40\1\41\7\27"+
    "\1\42\1\27\1\43\1\44\1\45\76\0\2\3\70\0"+
    "\1\3\5\0\1\6\1\0\1\6\1\0\4\6\3\0"+
    "\1\6\2\0\1\6\3\0\1\46\1\47\17\6\2\0"+
    "\21\6\1\0\1\6\5\0\1\6\1\0\1\6\1\0"+
    "\4\6\3\0\1\6\2\0\1\6\5\0\17\6\2\0"+
    "\21\6\1\0\1\6\10\0\1\7\7\0\1\7\2\0"+
    "\1\7\5\0\17\7\2\0\21\7\7\0\1\6\1\0"+
    "\1\6\1\0\4\6\3\0\1\6\2\0\1\6\3\0"+
    "\1\50\1\0\17\6\2\0\21\6\1\0\1\6\5\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\51\2\6\3\0"+
    "\1\6\2\0\1\6\5\0\17\6\2\0\21\6\1\0"+
    "\1\6\27\0\1\50\52\0\1\6\1\0\1\6\1\7"+
    "\4\6\3\0\1\52\2\0\1\52\3\0\1\50\1\0"+
    "\17\52\2\0\21\52\1\0\1\6\22\0\1\53\4\0"+
    "\1\50\52\0\1\6\1\0\1\6\1\0\4\6\3\0"+
    "\1\6\2\0\1\54\5\0\17\6\2\0\21\6\1\0"+
    "\1\6\5\0\1\55\20\0\2\46\74\0\1\46\74\0"+
    "\2\46\51\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\17\27\2\0\21\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\13\27\1\60"+
    "\3\27\2\0\21\27\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\0\4\56\3\0\1\56\1\57\1\0\1\56"+
    "\5\0\4\27\1\61\12\27\2\0\21\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\1\62\16\27\2\0\21\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\14\27\1\63"+
    "\2\27\2\0\21\27\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\7\4\56\3\0\1\64\1\57\1\0\1\64"+
    "\5\0\17\36\2\0\21\36\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\1\27\1\65\5\27\1\66"+
    "\11\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\17\27\1\67\1\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\12\27\1\70\6\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\17\27\2\0\15\27"+
    "\1\71\3\27\1\0\1\56\2\0\2\3\1\0\1\6"+
    "\1\0\1\6\1\0\4\6\3\0\1\6\2\0\1\6"+
    "\5\0\17\6\2\0\21\6\1\0\1\44\5\0\1\6"+
    "\1\0\1\6\1\7\4\6\3\0\1\52\2\0\1\52"+
    "\5\0\17\52\2\0\21\52\1\0\1\6\1\0\2\53"+
    "\2\0\71\53\4\0\1\6\1\0\1\6\1\0\4\6"+
    "\3\0\1\6\2\0\1\72\5\0\17\6\2\0\21\6"+
    "\1\0\1\6\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\2\0\1\56\5\0\17\56\2\0\21\56"+
    "\1\0\1\56\31\0\17\73\2\0\21\73\7\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\4\27\1\74\12\27\2\0\21\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\2\27\1\75\14\27"+
    "\2\0\21\27\1\0\1\56\5\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\14\27\1\76\2\27\2\0\21\27\1\0\1\56\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\15\27\1\77\1\27\2\0\21\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\7\4\56"+
    "\3\0\1\64\2\0\1\64\5\0\17\64\2\0\21\64"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\17\27\2\0"+
    "\10\27\1\100\10\27\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\0\4\56\3\0\1\56\1\57\1\0\1\56"+
    "\5\0\17\27\2\0\12\27\1\101\6\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\17\27\2\0\17\27\1\102"+
    "\1\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\7\27\1\103\11\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\20\27\1\104\1\0\1\56"+
    "\5\0\1\6\1\0\1\6\1\0\4\6\3\0\1\6"+
    "\2\0\1\105\5\0\17\6\2\0\21\6\1\0\1\6"+
    "\21\0\1\106\7\0\17\73\2\0\21\73\7\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\1\107\16\27\2\0\21\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\6\27\1\110\10\27\2\0"+
    "\21\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\14\27"+
    "\1\111\2\27\2\0\21\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\1\112\16\27\2\0\21\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\17\27\2\0\16\27\1\104"+
    "\2\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\1\113\20\27\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\0\4\56\3\0\1\56\1\57\1\0\1\56"+
    "\5\0\17\27\2\0\14\27\1\114\4\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\17\27\2\0\1\115\20\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\17\27\2\0"+
    "\4\27\1\116\14\27\1\0\1\56\5\0\1\6\1\0"+
    "\1\6\1\0\4\6\3\0\1\117\2\0\1\105\5\0"+
    "\17\6\2\0\21\6\1\0\1\6\54\0\1\120\25\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\13\27\1\121\3\27\2\0\21\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\1\122\16\27"+
    "\2\0\21\27\1\0\1\56\5\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\16\27\1\123\2\0\21\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\13\27\1\124\3\27\2\0\21\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\17\27\2\0\16\27"+
    "\1\125\2\27\1\0\1\56\5\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\16\27\1\126\2\27\1\0\1\56\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\17\27\2\0\16\27\1\127\2\27"+
    "\1\0\1\56\5\0\1\6\1\0\1\6\1\0\4\6"+
    "\3\0\1\6\2\0\1\130\5\0\17\6\2\0\21\6"+
    "\1\0\1\6\65\0\1\131\14\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\1\132\20\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\1\133\20\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\11\27\1\134\5\27\2\0"+
    "\21\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\7\27"+
    "\1\135\7\27\2\0\21\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\13\27\1\136\5\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\1\137\4\0\17\27\2\0"+
    "\21\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\13\27\1\140\5\27\1\0\1\56\5\0\1\6"+
    "\1\0\1\6\1\0\4\6\3\0\1\141\2\0\1\130"+
    "\5\0\17\6\2\0\21\6\1\0\1\6\63\0\1\142"+
    "\16\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\15\27\1\143\1\27\2\0"+
    "\21\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\2\27"+
    "\1\144\14\27\2\0\21\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\13\27\1\145\3\27\2\0\21\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\11\27\1\146\5\27"+
    "\2\0\21\27\1\0\1\56\5\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\10\27\1\147\10\27\1\0\1\56\22\0"+
    "\1\150\57\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\17\27\2\0\10\27"+
    "\1\151\10\27\1\0\1\56\5\0\1\6\1\0\1\6"+
    "\1\0\4\6\3\0\1\6\2\0\1\152\5\0\17\6"+
    "\2\0\21\6\1\0\1\6\22\0\1\153\57\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\14\27\1\154\2\27\2\0\21\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\13\27\1\155\3\27"+
    "\2\0\21\27\1\0\1\56\5\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\3\27\1\156\13\27\2\0\21\27\1\0\1\56\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\17\27\2\0\7\27\1\157\11\27"+
    "\1\0\1\56\22\0\1\160\57\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\7\27\1\161\11\27\1\0\1\56\5\0"+
    "\1\153\1\0\1\153\1\0\4\153\3\0\1\153\1\0"+
    "\2\153\5\0\17\153\2\0\21\153\1\0\1\153\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\15\27\1\162\1\27\2\0\21\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\4\27\1\163"+
    "\12\27\2\0\21\27\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\0\4\56\3\0\1\56\1\57\1\0\1\56"+
    "\5\0\17\27\2\0\2\27\1\164\16\27\1\0\1\56"+
    "\31\0\17\165\2\0\21\165\7\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\2\27\1\166\16\27\1\0\1\56\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\1\167\16\27\2\0\21\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\1\170\16\27\2\0"+
    "\21\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\7\27\1\171\11\27\1\0\1\56\21\0\1\57"+
    "\7\0\17\165\2\0\21\165\7\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\7\27\1\172\11\27\1\0\1\56\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\5\0\13\27\1\173\3\27\2\0\21\27"+
    "\1\0\1\56\5\0\1\56\1\0\1\56\1\0\4\56"+
    "\3\0\1\56\1\57\1\0\1\56\5\0\2\27\1\174"+
    "\14\27\2\0\21\27\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\0\4\56\3\0\1\56\1\57\1\0\1\56"+
    "\5\0\17\27\2\0\17\27\1\175\1\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\17\27\2\0\17\27\1\176"+
    "\1\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\7\27"+
    "\1\177\7\27\2\0\21\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\7\27\1\200\7\27\2\0\21\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\17\27\2\0\20\27"+
    "\1\201\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\20\27\1\202\1\0\1\56\5\0\1\56\1\0"+
    "\1\56\1\0\4\56\3\0\1\56\1\57\1\0\1\56"+
    "\5\0\11\27\1\203\5\27\2\0\21\27\1\0\1\56"+
    "\5\0\1\56\1\0\1\56\1\0\4\56\3\0\1\56"+
    "\1\57\1\0\1\56\5\0\11\27\1\204\5\27\2\0"+
    "\21\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\3\27\1\205\15\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\3\27\1\206\15\27\1\0"+
    "\1\56\5\0\1\56\1\0\1\56\1\0\4\56\3\0"+
    "\1\56\1\57\1\0\1\56\5\0\10\27\1\207\6\27"+
    "\2\0\21\27\1\0\1\56\5\0\1\56\1\0\1\56"+
    "\1\0\4\56\3\0\1\56\1\57\1\0\1\56\5\0"+
    "\17\27\2\0\4\27\1\210\14\27\1\0\1\56\5\0"+
    "\1\56\1\0\1\56\1\0\4\56\3\0\1\56\1\57"+
    "\1\0\1\56\1\211\4\0\17\27\2\0\4\27\1\212"+
    "\14\27\1\0\1\56\5\0\1\56\1\0\1\56\1\0"+
    "\4\56\3\0\1\56\1\57\1\0\1\56\5\0\17\27"+
    "\2\0\16\27\1\213\2\27\1\0\1\56\5\0\1\56"+
    "\1\0\1\56\1\0\4\56\3\0\1\56\1\57\1\0"+
    "\1\56\5\0\17\27\2\0\16\27\1\214\2\27\1\0"+
    "\1\56\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7015];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\10\1\1\11\3\1\2\11"+
    "\10\1\2\11\5\1\1\11\1\1\4\11\4\1\1\11"+
    "\1\1\1\0\13\1\1\0\12\1\1\0\11\1\1\0"+
    "\10\1\1\0\5\1\1\0\2\1\1\0\5\1\1\0"+
    "\7\1\1\0\4\1\1\0\23\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[140];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(sym.ERROR, yycolumn, yyline, yytext());
            }
            // fall through
          case 40: break;
          case 2:
            { /*Ignore*/
            }
            // fall through
          case 41: break;
          case 3:
            { return new Symbol(sym.Op_logico, yycolumn, yyline, yytext());
            }
            // fall through
          case 42: break;
          case 4:
            { return new Symbol(sym.Comillas, yycolumn, yyline, yytext());
            }
            // fall through
          case 43: break;
          case 5:
            { return new Symbol(sym.Contra,yycolumn,yyline,yytext());
            }
            // fall through
          case 44: break;
          case 6:
            { System.out.println("ID encontrado");return new Symbol(sym.ID,yycolumn,yyline,yytext());
            }
            // fall through
          case 45: break;
          case 7:
            { return new Symbol(sym.Parentesis_a, yycolumn, yyline, yytext());
            }
            // fall through
          case 46: break;
          case 8:
            { return new Symbol(sym.Parentesis_c, yycolumn, yyline, yytext());
            }
            // fall through
          case 47: break;
          case 9:
            { return new Symbol(sym.Multiplicacion, yycolumn, yyline, yytext());
            }
            // fall through
          case 48: break;
          case 10:
            { return new Symbol(sym.Suma, yycolumn, yyline, yytext());
            }
            // fall through
          case 49: break;
          case 11:
            { return new Symbol(sym.Coma, yycolumn, yyline, yytext());
            }
            // fall through
          case 50: break;
          case 12:
            { return new Symbol(sym.Resta, yycolumn, yyline, yytext());
            }
            // fall through
          case 51: break;
          case 13:
            { return new Symbol(sym.Division, yycolumn, yyline, yytext());
            }
            // fall through
          case 52: break;
          case 14:
            { System.out.println("numero correcto");return new Symbol(sym.Numero, yycolumn, yyline, yytext());
            }
            // fall through
          case 53: break;
          case 15:
            { return new Symbol(sym.DosP, yycolumn, yyline, yytext());
            }
            // fall through
          case 54: break;
          case 16:
            { return new Symbol(sym.P_coma, yycolumn, yyline, yytext());
            }
            // fall through
          case 55: break;
          case 17:
            { return new Symbol(sym.MenorQ,yycolumn,yyline,yytext());
            }
            // fall through
          case 56: break;
          case 18:
            { return new Symbol(sym.Igual, yycolumn, yyline, yytext());
            }
            // fall through
          case 57: break;
          case 19:
            { return new Symbol(sym.MayorQ,yycolumn,yyline,yytext());
            }
            // fall through
          case 58: break;
          case 20:
            { System.out.println("usuario correcto");return new Symbol(sym.Usuario,yycolumn,yyline,yytext());
            }
            // fall through
          case 59: break;
          case 21:
            { return new Symbol(sym.Corchete_a, yycolumn, yyline, yytext());
            }
            // fall through
          case 60: break;
          case 22:
            { return new Symbol(sym.Corchete_c, yycolumn, yyline, yytext());
            }
            // fall through
          case 61: break;
          case 23:
            { return new Symbol(sym.Llave_a, yycolumn, yyline, yytext());
            }
            // fall through
          case 62: break;
          case 24:
            { return new Symbol(sym.Llave_c, yycolumn, yyline, yytext());
            }
            // fall through
          case 63: break;
          case 25:
            { return new Symbol(sym.Op_relacional, yycolumn, yyline, yytext());
            }
            // fall through
          case 64: break;
          case 26:
            { return new Symbol(sym.FinE,yycolumn,yyline,yytext());
            }
            // fall through
          case 65: break;
          case 27:
            { return new Symbol(sym.Op_atribucion, yycolumn, yyline, yytext());
            }
            // fall through
          case 66: break;
          case 28:
            { return new Symbol(sym.InicioE,yycolumn,yyline,yytext());
            }
            // fall through
          case 67: break;
          case 29:
            { return new Symbol(sym.Op_booleano, yycolumn, yyline, yytext());
            }
            // fall through
          case 68: break;
          case 30:
            { return new Symbol(sym.UsuarioP,yycolumn,yyline,yytext());
            }
            // fall through
          case 69: break;
          case 31:
            { System.out.println("fecha correcta");return new Symbol(sym.Fecha,yycolumn,yyline,yytext());
            }
            // fall through
          case 70: break;
          case 32:
            { System.out.println("URL");return new Symbol(sym.URL, yycolumn,yyline,yytext());
            }
            // fall through
          case 71: break;
          case 33:
            { return new Symbol(sym.ContraP,yycolumn,yyline,yytext());
            }
            // fall through
          case 72: break;
          case 34:
            { System.out.println("Crear usuario");return new Symbol(sym.CrearU,yycolumn,yyline,yytext());
            }
            // fall through
          case 73: break;
          case 35:
            { return new Symbol(sym.FinSolicitud,yycolumn,yyline,yytext());
            }
            // fall through
          case 74: break;
          case 36:
            { return new Symbol(sym.FechaCP,yycolumn,yyline,yytext());
            }
            // fall through
          case 75: break;
          case 37:
            { System.out.println("inicio de solicitud correcta");return new Symbol(sym.InicioSolicitud, yycolumn, yyline, yytext());
            }
            // fall through
          case 76: break;
          case 38:
            { return new Symbol(sym.FinMasSolicitudes, yycolumn, yyline, yytext());
            }
            // fall through
          case 77: break;
          case 39:
            { return new Symbol(sym.MasSolicitudes, yycolumn, yyline, yytext());
            }
            // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
