
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 18;
  public static final int Coma = 40;
  public static final int Llave_c = 29;
  public static final int Op_booleano = 22;
  public static final int Llave_a = 28;
  public static final int FinSolicitud = 39;
  public static final int ContraP = 19;
  public static final int Corchete_c = 31;
  public static final int Corchete_a = 30;
  public static final int MenorQ = 8;
  public static final int UsuarioP = 11;
  public static final int Division = 16;
  public static final int Cadena = 9;
  public static final int Parentesis_c = 24;
  public static final int ID = 41;
  public static final int Parentesis_a = 23;
  public static final int CrearU = 10;
  public static final int EOF = 0;
  public static final int P_coma = 32;
  public static final int error = 1;
  public static final int InicioSolicitud = 38;
  public static final int Linea = 2;
  public static final int URL = 42;
  public static final int MasSolicitudes = 34;
  public static final int Op_atribucion = 21;
  public static final int ERROR = 37;
  public static final int Op_logico = 17;
  public static final int Contra = 26;
  public static final int DosP = 5;
  public static final int Usuario = 25;
  public static final int InicioE = 4;
  public static final int Identificador = 33;
  public static final int Resta = 14;
  public static final int Fecha = 27;
  public static final int Multiplicacion = 15;
  public static final int Numero = 36;
  public static final int Suma = 13;
  public static final int FinMasSolicitudes = 35;
  public static final int FinE = 6;
  public static final int Igual = 12;
  public static final int FechaCP = 20;
  public static final int MayorQ = 7;
  public static final int Comillas = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linea",
  "Comillas",
  "InicioE",
  "DosP",
  "FinE",
  "MayorQ",
  "MenorQ",
  "Cadena",
  "CrearU",
  "UsuarioP",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Op_logico",
  "Op_relacional",
  "ContraP",
  "FechaCP",
  "Op_atribucion",
  "Op_booleano",
  "Parentesis_a",
  "Parentesis_c",
  "Usuario",
  "Contra",
  "Fecha",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "P_coma",
  "Identificador",
  "MasSolicitudes",
  "FinMasSolicitudes",
  "Numero",
  "ERROR",
  "InicioSolicitud",
  "FinSolicitud",
  "Coma",
  "ID",
  "URL"
  };
}

