/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.google.gson.Gson;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.ScrollPaneConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultCaret;
import javax.swing.text.Element;
import org.apache.hc.client5.http.classic.HttpClient;
import org.apache.hc.client5.http.classic.methods.HttpPost;
import org.apache.hc.client5.http.entity.UrlEncodedFormEntity;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.core5.http.NameValuePair;
import org.apache.hc.core5.http.ParseException;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.http.io.entity.StringEntity;
import org.apache.hc.core5.http.message.BasicNameValuePair;
import java.nio.charset.StandardCharsets;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author willi
 */
public class Creacion extends javax.swing.JFrame {

    private static JTextArea textArea;
    private static JTextArea lines;
    private JScrollPane jsp;
    private static JTextArea textArea2;
    private static JTextPane textPane;
    private static JTextPane textPane2;
    private static JTextArea lines2;
    private JScrollPane jsp2;
    private String logeado;
    private ArrayList<Reporte> reportes = new ArrayList<>();
    private int report_actual = 0;

    /**
     * Creates new form Creacion
     */
    public Creacion() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        btn_reportes.setVisible(false);
        logeado = "";
        jsp = new JScrollPane();
        textArea = new JTextArea();
        TextLineNumber tln = new TextLineNumber(textArea);
        tln.setBorderGap(1);
        tln.setBackground(Color.BLACK);
        tln.setForeground(Color.WHITE);
        tln.setCurrentLineForeground(Color.YELLOW);
        textArea.setBackground(new Color(97, 97, 97));
        jsp.getViewport().add(textArea);
        jsp.setBorder(null);
        jsp.setRowHeaderView(tln);
        jsp.setBounds(0, 0, pan1.getWidth(), pan1.getHeight());
        pan1.add(jsp);
        jtab.setEnabledAt(2, false);
        jtab.setEnabledAt(1, false);

        jsp2 = new JScrollPane();
        textArea2 = new JTextArea();
        textArea2.setBackground(new Color(97, 97, 97));
        textPane = new JTextPane();
        textPane.setOpaque(false);
        textPane.setBackground(new Color(97, 97, 97));
        jsp2.getViewport().add(textArea2);
        TextLineNumber tln2 = new TextLineNumber(textArea2);
        tln2.setBorderGap(1);
        tln2.setBackground(Color.BLACK);
        tln2.setForeground(Color.WHITE);
        tln2.setCurrentLineForeground(Color.YELLOW);
        jsp2.setRowHeaderView(tln2);
        jsp2.setBorder(null);
        jsp2.setBounds(0, 0, pan2.getWidth(), pan2.getHeight());
        pan2.add(jsp2);
        pan2.setBackground(new Color(97, 97, 97));

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cargar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jlabel_path = new javax.swing.JLabel();
        pan1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pan2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_reportes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlabel_consulta = new javax.swing.JLabel();
        jlabel_id = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WForms");
        setBackground(new java.awt.Color(25, 25, 25));
        setMinimumSize(new java.awt.Dimension(620, 510));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jtab.setBackground(new java.awt.Color(25, 25, 25));
        jtab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setBackground(new java.awt.Color(25, 25, 25));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(216, 255, 144));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AREA DE INGRESO DE SOLICITUDES");

        btn_cargar.setBackground(new java.awt.Color(25, 25, 25));
        btn_cargar.setForeground(new java.awt.Color(216, 255, 144));
        btn_cargar.setText("<html>CARGAR<br>ARCHIVO</html>");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(25, 25, 25));
        btn_limpiar.setForeground(new java.awt.Color(216, 255, 144));
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.setEnabled(false);
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        jlabel_path.setForeground(new java.awt.Color(216, 255, 144));
        jlabel_path.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_path.setText("-");

        pan1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pan1ComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pan1ComponentShown(evt);
            }
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setBackground(new java.awt.Color(25, 25, 25));
        jButton1.setForeground(new java.awt.Color(216, 255, 144));
        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(25, 25, 25));
        btn_login.setForeground(new java.awt.Color(255, 0, 0));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/offrz.png"))); // NOI18N
        btn_login.setText("<html>SIN<br>LOGIN</html>");
        btn_login.setContentAreaFilled(false);
        btn_login.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/img/offrz.png"))); // NOI18N
        btn_login.setEnabled(false);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(25, 25, 25));
        jButton2.setForeground(new java.awt.Color(216, 255, 144));
        jButton2.setText("GUARDAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_cargar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_login, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jlabel_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel_path, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(242, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))))
        );

        jtab.addTab("AREA SOLICITUDES", jPanel1);

        jPanel3.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(216, 255, 144));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RESPUESTA DEL SERVIDOR");

        btn_reportes.setText("VER REPORTES (0)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtab.addTab("AREA RESPUESTA", jPanel3);

        jPanel2.setBackground(new java.awt.Color(25, 25, 25));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(216, 255, 144));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AREA DE DESPLIEGUE DE REPORTES");

        jlabel_consulta.setForeground(new java.awt.Color(216, 255, 144));
        jlabel_consulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_consulta.setText("ACÁ APARECERA EL NOMBRE DE LA CONSULTA");

        jlabel_id.setForeground(new java.awt.Color(216, 255, 144));
        jlabel_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel_id.setText("ACÁ APARECERA EL ID DE LA CONSULTA");

        btn_anterior.setText("A");
        btn_anterior.setEnabled(false);

        btn_siguiente.setText("S");
        btn_siguiente.setEnabled(false);
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        tabla_reporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_reporte);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addComponent(jlabel_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_siguiente)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel_id)
                .addGap(12, 12, 12)
                .addComponent(jlabel_consulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_anterior)
                            .addComponent(btn_siguiente))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtab.addTab("AREA REPORTES", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        textArea.setText("");
        jlabel_path.setText("");
        btn_limpiar.setEnabled(false);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Archivos de texto", "txt");
        chooser.setFileFilter(filtro2);
        int resultado = chooser.showOpenDialog(this);
        if (resultado == 0) {
            File archivo = new File(chooser.getSelectedFile().getAbsolutePath());
            String path = chooser.getSelectedFile().getAbsolutePath();
            String nuevo = path;
            jlabel_path.setText("Archivo cargado: " + nuevo);
            String ST;
            try {
                ST = new String(Files.readAllBytes(archivo.toPath()));
                textArea.setText(ST);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            btn_limpiar.setEnabled(true);
        } else {
            jlabel_path.setText("");
            btn_limpiar.setEnabled(false);
        }
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void pan1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pan1ComponentResized
        jsp.setBounds(0, 0, pan1.getWidth(), pan1.getHeight());
    }//GEN-LAST:event_pan1ComponentResized

    private void pan1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pan1ComponentShown
        jsp.setBounds(0, 0, pan1.getWidth(), pan1.getHeight());
    }//GEN-LAST:event_pan1ComponentShown

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jsp.setBounds(0, 0, pan1.getWidth(), pan1.getHeight());
        jsp2.setBounds(0, 0, pan2.getWidth(), pan2.getHeight());
        String txt1 = textArea.getText();
        String txt2 = textArea2.getText();
        textArea.setEditable(false);
        textArea2.setEditable(false);
        textArea.setEditable(true);
        textArea2.setEditable(true);
    }//GEN-LAST:event_formComponentResized

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            comunicacionServidor();
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String[] options = {"SI", "NO"};
        int x = JOptionPane.showOptionDialog(null, "¿Estás seguro de cerrar sesión?",
                "CERRAR SESION",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, new ImageIcon("C:\\Users\\willi\\OneDrive\\Documentos\\NetBeansProjects\\Forms\\src\\img\\arrow.png"), options, options[0]);
        if (x == 0) {
            setLogeado("");
            btn_login.setText("<html><font color=red>SIN</font><br><font color =red>LOGIN</font></html>");
            btn_login.setEnabled(false);
            btn_login.setContentAreaFilled(false);
            btn_login.setIcon(new ImageIcon("C:\\Users\\willi\\OneDrive\\Documentos\\NetBeansProjects\\Forms\\src\\img\\offrz.png"));
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        if ((report_actual + 1) != (reportes.size())) {
            report_actual++;

        } else {
            report_actual = 0;
        }
        System.out.println(reportes.size());
        Object[] objArray = reportes.get(report_actual).getColumnas().toArray();
        ArrayList<String> d = reportes.get(report_actual).getDatos();
        jlabel_id.setText(reportes.get(report_actual).getId_consulta());
        jlabel_consulta.setText(reportes.get(report_actual).getConsulta());
        DefaultTableModel dtm = new DefaultTableModel(objArray, 0);
        ArrayList<String> escribiendo = new ArrayList<>();
        int conteo = 0;
        for (int i = 0; i < d.size(); i++) {
            if (conteo == (objArray.length - 1)) {
                escribiendo.add(d.get(i));
                dtm.addRow(escribiendo.toArray());
                escribiendo = new ArrayList<>();
                conteo = 0;
            } else {
                escribiendo.add(d.get(i));
                conteo++;
            }
        }
        tabla_reporte.setModel(dtm);
    }//GEN-LAST:event_btn_siguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion().setVisible(true);
            }
        });
    }

    public void comunicacionServidor() throws Exception {
        try (final CloseableHttpClient httpclient = HttpClients.createDefault()) {
            final HttpPost httppost = new HttpPost("http://localhost:8080/WForms/Creacion");
            List<NameValuePair> params = new ArrayList<>(2);

            String texto = textArea.getText();
            //posicionar(10,18);
            params.add(new BasicNameValuePair("entrada", texto));
            params.add(new BasicNameValuePair("usuario", "ozymandias"));
            httppost.setEntity(new UrlEncodedFormEntity(params, StandardCharsets.UTF_8));
            System.out.println("Executing request " + httppost.getMethod() + " " + httppost.getUri());
            try (final CloseableHttpResponse response = httpclient.execute(httppost)) {
                System.out.println("----------------------------------------");
                System.out.println(response.getCode() + " " + response.getReasonPhrase());
                String respuesta = EntityUtils.toString(response.getEntity(), StandardCharsets.UTF_8);
                Gson gson = new Gson();
                Map<String, String> map = gson.fromJson(respuesta, Map.class);
                if (!map.containsKey("ERROR")) {
                    textArea2.setText(map.get("respuesta"));
                    if (map.containsKey("reportes")) {
                        reportes = new ArrayList<>();
                        String[] partes_consulta = map.get("reportes").split("\t");
                        for (String part : partes_consulta) {
                            String[] parti = part.split("\n");
                            Reporte nuevo = new Reporte();
                            nuevo.setId_consulta(parti[0]);
                            nuevo.setConsulta(parti[1]);
                            System.out.println(nuevo.getConsulta());
                            System.out.println(parti[2]);
                            String[] cols = parti[2].split("<///>");
                            for (String col : cols) {
                                nuevo.getColumnas().add(col);
                            }
                            nuevo.setNoColumnas(nuevo.getColumnas().size());
                            String[] dat = parti[3].split("<///>");
                            for (String col : dat) {
                                nuevo.getDatos().add(col);
                                System.out.println(col);
                            }
                            reportes.add(nuevo);
                        }
                        if (!reportes.isEmpty()) {
                            Object[] objArray = reportes.get(0).getColumnas().toArray();
                            ArrayList<String> d = reportes.get(0).getDatos();
                            jlabel_id.setText(reportes.get(0).getId_consulta());
                            jlabel_consulta.setText(reportes.get(0).getConsulta());
                            DefaultTableModel dtm = new DefaultTableModel(objArray, 0);
                            ArrayList<String> escribiendo = new ArrayList<>();
                            int conteo = 0;
                            for (int i = 0; i < d.size(); i++) {
                                if (conteo == (objArray.length - 1)) {
                                    escribiendo.add(d.get(i));
                                    dtm.addRow(escribiendo.toArray());
                                    escribiendo = new ArrayList<>();
                                    conteo = 0;
                                } else {
                                    escribiendo.add(d.get(i));
                                    conteo++;
                                }
                            }
                            tabla_reporte.setModel(dtm);
                            report_actual = 0;
                            if (reportes.size() > 1) {
                                btn_siguiente.setEnabled(true);
                            }
                        }
                        btn_reportes.setVisible(true);
                        btn_reportes.setText("VER REPORTES (" + reportes.size() + ")");
                    }
                    jtab.setSelectedIndex(1);
                    jtab.setEnabledAt(1, true);
                    jtab.setEnabledAt(2, true);
                    setLogeado(map.get("usuario"));
                    btn_login.setText("<html><span style=\"color: #D8FF90; font-size: 7px;\">CERRAR</span><br><span style=\"color: #D8FF90; font-size: 7px;\">SESION</span></html>");
                    btn_login.setEnabled(true);
                    btn_login.setContentAreaFilled(true);
                    btn_login.setIcon(new ImageIcon("C:\\Users\\willi\\OneDrive\\Documentos\\NetBeansProjects\\Forms\\src\\img\\onrz.png"));
                } else {
                    JOptionPane.showMessageDialog(null, map.get("ERROR"));
                }
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        } catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void posicionar(int linea, int columna) {
        String texto = textArea.getText();
        String[] lineas1 = texto.split("\n");
        int[] cuantos = new int[lineas1.length];
        for (int i = 0; i < lineas1.length; i++) {
            cuantos[i] = lineas1[i].length();
        }
        int donde = 0;
        for (int i = 0; i < (linea - 1); i++) {
            donde += cuantos[i] + 1;
        }
        donde += (columna - 1);
        textArea.setCaretPosition(donde);
    }

    public String getLogeado() {
        return logeado;
    }

    public void setLogeado(String logeado) {
        this.logeado = logeado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel_consulta;
    private javax.swing.JLabel jlabel_id;
    private javax.swing.JLabel jlabel_path;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JTable tabla_reporte;
    // End of variables declaration//GEN-END:variables
}
